version: '3.8'

services:
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always

  backend:
    build:
      context: ./Server
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    environment:
      - TRUST_PROXY=true
      - DOCKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGINS=http://localhost:5173
    depends_on:
      - redis
    volumes:
      - ./Server:/app
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis-blog
    ports:
      - "6379:6379"
    restart: always
